version: '2.12.2'

services:
 
  ng_cash_server:
    container_name: ng_cash_app
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/ng_cash_app
    environment:
      - DATABASE_URL="ng_cash_user:ng_cash_pass@postgres:5432/ng_cash_db"
      - PORT=3333