version: '2.12.2'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - "POSTGRES_PASSWORD=ng_cash_pass"
      - "POSTGRES_USER=ng_cash_user"
      - "POSTGRES_DB=ng_cash_db"
    ports:
      - "5432:5432"
  ng_cash_app:
    container_name: ng_cash_app
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/ng_cash_app
    environment:
      - DATABASE_URL="ng_cash_user:ng_cash_pass@postgres:5432/ng_cash_db"
      - PORT=3333