version: '2.12.2'

services:
 
  ng_cash_server:
    container_name: ng_cash_server
    build: ./server
    restart: always
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - .:/ng_cash_server
    environment:
      - DATABASE_URL="postgresql://ng_cash_user:ng_cash_pass@localhost:5432/ng_cash_db?schema=public"
      - PORT=3333
      - JWT_SECRET="azzsdgdsgsgregea"

  ng_cash_client:
    container_name: ng_cash_client
    build: ./client
    restart: always
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/ng_cash_client
    environment:
      - VITE_API_URL='http://127.0.0.1:3333'

